version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "yc-sls-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1isplxvx6e22x"
s3_prefix = "yc-sls-backend"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
